---
- name: Install Apache Pkg. on RedHat Family
  yum: name=httpd state=present
  when: ansible_os_family == "RedHat"

- name: Install Apache Pkg. on Debain Family
  apt: name=apache2 state=present
  when: ansible_os_family == "Debain"
