---
- hosts: db
  sudo: yes

  tasks: 
  - name: Install MariaDB Pkg.
    yum: name=mariadb-server state=present

  - name: Start the Apache Service
    service: name=mariadb state=started enabled=True
